services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: unless-stopped
    ports:
      - "0.0.0.0:${KUMA_PORT:-3002}:3001/tcp"
    environment:
      - TZ=${TIMEZONE:-Europe/Moscow}
    volumes:
      - ../../../volumes/uptime-kuma/data:/app/data
    networks:
      - kuma-net

networks:
  kuma-net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "0.0.0.0"


