services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "0.0.0.0:80:80/tcp"
      - "0.0.0.0:443:443/tcp"
    environment:
      - TZ=${TIMEZONE:-Europe/Moscow}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ../../../volumes/caddy/data:/data
      - ../../../volumes/caddy/config:/config
    networks:
      - caddy-net

networks:
  caddy-net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "0.0.0.0"


